[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/test/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "backendex"

[services.source]
repo = "."

[services.variables]
NODE_ENV = "production"
